name: mDNS Advertiser
version: "0.0.12"
slug: mdns_advertiser
description: Selectively advertises HA services via mDNS on a specific interface
url: "https://github.com/YeonV/home-assistant-addons/tree/main/mdns-advertiser" # Update with your repo URL
arch:
  - aarch64
  - amd64
  # - armhf
  - armv7
init: false
homeassistant_api: true # Needed to get Home Assistant token & access internal API
hassio_api: true # Needed to get Supervisor token & access internal API
hassio_role: manager # Standard role sufficient for API access
options:
  interface: "eth0"
  update_interval: 300
  log_level: "info"
  services: [] # Default to empty list
schema:
  interface: str
  update_interval: int(60,)
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  services: # List of service rules
    - name: str # User-friendly name for this rule
      enabled: bool? # Optional, default true
      # --- NEW: Specify entities directly ---
      entities: # List of entity IDs to advertise
        - str
      # --- END NEW ---
      service_type: str # mDNS service type (_wled._tcp)
      service_port: int(1,65535) # mDNS service port (80)
      # --- NEW: Source Selection ---
      ip_source: list(state|attribute)? # Default: attribute
      ip_attribute: str? # Required if ip_source is 'attribute'
      name_source: list(attribute|entity_id)? # Default: attribute
      name_attribute: str? # Required if name_source is 'attribute', default 'friendly_name'
      # --- END NEW ---
      filter_by_state: str? # Optional: state value to filter OUT (e.g., "unavailable")
      filter_by_state_inverse: bool? # Optional: set true to KEEP states NOT matching filter_by_state (default false)
      # txt_records: # Optional complex structure
      #   - key: str
      #     attribute: str
image: ghcr.io/yeonv/{arch}-addon-mdns_advertiser